/*
트랜잭션의 고립수준
4가지 고립수준 : 수준 0 ~ 수준 3
고립 유형 : 오손 데이터 읽기, 반복 불가능 읽기, 유령 데이터 읽기
*/

/*
SET TRANSACTION ISOLATION LEVEL 문
고립수준을 정의하는 명령문의 형식
SET TRANSACTION ISOLATION LEVEL 고립_수준_키워드;
*/

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;	-- 고립수준 0
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;		-- 고립수준 1
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;	-- 고립수준 2
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;		-- 고립수준 3